# Generated by Django 5.0.2 on 2024-03-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pass1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='pass2',
        ),
    ]
